import type { Movie, TvProgram, PersonResult } from "./types";

export const DEMO_MOVIES: Movie[] = [
  {
    id: "d1",
    title: "Border",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/8e/Border_film_poster.jpg",
    releaseDate: "1997-06-13",
    year: 1997,
    runtime: 176,
    genres: ["Action", "War", "Drama"],
    language: "Hindi",
    rating: 7.9,
    director: "J.P. Dutta",
    actors: [{ name: "Sunny Deol", character: "Kuldeep Singh" }],
    description: "Classic war drama based on the Battle of Longewala, 1971.",
    platforms: [{ name: "JioHotstar", status: "subscription", url: "https://www.hotstar.com" }],
    isFree: false,
    popularity: 90,
  },
  {
    id: "d2",
    title: "Shershaah",
    poster: "https://upload.wikimedia.org/wikipedia/en/2/2e/Shershaah.jpg",
    releaseDate: "2021-08-12",
    year: 2021,
    runtime: 135,
    genres: ["Action", "Biography", "War"],
    language: "Hindi",
    rating: 8.4,
    director: "Vishnuvardhan",
    actors: [{ name: "Sidharth Malhotra", character: "Vikram Batra" }],
    description: "Story of PVC recipient Captain Vikram Batra during Kargil War.",
    platforms: [{ name: "JioHotstar", status: "subscription", url: "https://www.hotstar.com" }],
    isFree: false,
    popularity: 88,
  },
  {
    id: "d3",
    title: "3 Idiots",
    poster: "https://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg",
    releaseDate: "2009-12-25",
    year: 2009,
    runtime: 170,
    genres: ["Comedy", "Drama"],
    language: "Hindi",
    rating: 8.4,
    director: "Rajkumar Hirani",
    actors: [{ name: "Aamir Khan", character: "Rancho" }],
    description: "Two friends search for their long-lost companion while recalling college days.",
    platforms: [
      { name: "Netflix", status: "subscription", url: "https://www.netflix.com" },
      { name: "YouTube", status: "free", url: "https://www.youtube.com" },
    ],
    isFree: true,
    popularity: 95,
  },
  {
    id: "d4",
    title: "Dangal",
    poster: "https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg",
    releaseDate: "2016-12-23",
    year: 2016,
    runtime: 161,
    genres: ["Biography", "Drama", "Sport"],
    language: "Hindi",
    rating: 8.3,
    director: "Nitesh Tiwari",
    actors: [{ name: "Aamir Khan", character: "Mahavir Singh Phogat" }],
    description: "Former wrestler trains his daughters to become world-class wrestlers.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 92,
  },
  {
    id: "d5",
    title: "Pathaan",
    poster: "https://upload.wikimedia.org/wikipedia/en/c/c3/Pathaan_film_poster.jpg",
    releaseDate: "2023-01-25",
    year: 2023,
    runtime: 146,
    genres: ["Action", "Thriller"],
    language: "Hindi",
    rating: 6.0,
    director: "Siddharth Anand",
    actors: [{ name: "Shah Rukh Khan", character: "Pathaan" }],
    description: "An exiled RAW agent partners with an assassin to stop a deadly attack.",
    platforms: [{ name: "JioHotstar", status: "subscription", url: "https://www.hotstar.com" }],
    isFree: false,
    popularity: 85,
  },
  {
    id: "d6",
    title: "Jawan",
    poster: "https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Jawan_film_poster.jpg/220px-Jawan_film_poster.jpg",
    releaseDate: "2023-09-07",
    year: 2023,
    runtime: 169,
    genres: ["Action", "Thriller"],
    language: "Hindi",
    rating: 7.0,
    director: "Atlee",
    actors: [{ name: "Shah Rukh Khan", character: "" }],
    description: "A man seeks justice against corruption that destroyed his family.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 87,
  },
  {
    id: "d7",
    title: "Uri: The Surgical Strike",
    poster: "https://upload.wikimedia.org/wikipedia/en/3/3b/URI_-_New_poster.jpg",
    releaseDate: "2019-01-11",
    year: 2019,
    runtime: 138,
    genres: ["Action", "Drama", "War"],
    language: "Hindi",
    rating: 8.2,
    director: "Aditya Dhar",
    actors: [{ name: "Vicky Kaushal", character: "" }],
    description: "Indian army special forces execute a surgical strike after Uri attack.",
    platforms: [{ name: "JioHotstar", status: "subscription", url: "https://www.hotstar.com" }],
    isFree: false,
    popularity: 86,
  },
  {
    id: "d8",
    title: "Andhadhun",
    poster: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Andhadhun.jpg/220px-Andhadhun.jpg",
    releaseDate: "2018-10-05",
    year: 2018,
    runtime: 139,
    genres: ["Crime", "Thriller", "Comedy"],
    language: "Hindi",
    rating: 8.2,
    director: "Sriram Raghavan",
    actors: [{ name: "Ayushmann Khurrana", character: "" }],
    description: "A blind pianist becomes entangled in a series of murders.",
    platforms: [
      { name: "Netflix", status: "subscription", url: "https://www.netflix.com" },
      { name: "YouTube", status: "free", url: "https://www.youtube.com" },
    ],
    isFree: true,
    popularity: 84,
  },
  {
    id: "d9",
    title: "Gangs of Wasseypur",
    poster: "https://upload.wikimedia.org/wikipedia/en/6/6a/Gangs_of_Wasseypur_poster.jpg",
    releaseDate: "2012-06-22",
    year: 2012,
    runtime: 160,
    genres: ["Crime", "Action", "Drama"],
    language: "Hindi",
    rating: 8.2,
    director: "Anurag Kashyap",
    actors: [{ name: "Manoj Bajpayee", character: "" }],
    description: "A coal mafia family feud spanning generations in Wasseypur.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 83,
  },
  {
    id: "d10",
    title: "Lagaan",
    poster: "https://upload.wikimedia.org/wikipedia/en/b/b6/Lagaan.jpg",
    releaseDate: "2001-06-15",
    year: 2001,
    runtime: 224,
    genres: ["Drama", "Sport"],
    language: "Hindi",
    rating: 8.1,
    director: "Ashutosh Gowariker",
    actors: [{ name: "Aamir Khan", character: "" }],
    description: "Villagers challenge British officers to a cricket match to avoid tax.",
    platforms: [{ name: "YouTube", status: "free", url: "https://www.youtube.com" }],
    isFree: true,
    popularity: 80,
  },
  {
    id: "d11",
    title: "Dilwale Dulhania Le Jayenge",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/80/Dilwale_Dulhania_Le_Jayenge_poster.jpg",
    releaseDate: "1995-10-20",
    year: 1995,
    runtime: 189,
    genres: ["Romance", "Drama"],
    language: "Hindi",
    rating: 8.0,
    director: "Aditya Chopra",
    actors: [
      { name: "Shah Rukh Khan", character: "Raj" },
      { name: "Kajol", character: "Simran" },
    ],
    description: "A young man and woman fall in love on a trip to Europe.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 91,
  },
  {
    id: "d12",
    title: "Taare Zameen Par",
    poster: "https://upload.wikimedia.org/wikipedia/en/b/b3/Taare_Zameen_Par_poster.jpg",
    releaseDate: "2007-12-21",
    year: 2007,
    runtime: 165,
    genres: ["Drama", "Family"],
    language: "Hindi",
    rating: 8.3,
    director: "Aamir Khan",
    actors: [
      { name: "Darsheel Safary", character: "" },
      { name: "Aamir Khan", character: "" },
    ],
    description: "An art teacher helps a dyslexic child discover his potential.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 82,
  },
  {
    id: "d13",
    title: "Barfi!",
    poster: "https://upload.wikimedia.org/wikipedia/en/2/2e/Barfi%21_poster.jpg",
    releaseDate: "2012-09-14",
    year: 2012,
    runtime: 151,
    genres: ["Comedy", "Drama", "Romance"],
    language: "Hindi",
    rating: 8.1,
    director: "Anurag Basu",
    actors: [{ name: "Ranbir Kapoor", character: "" }],
    description: "The life of a deaf-mute man and the two women who love him.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 78,
  },
  {
    id: "d14",
    title: "Queen",
    poster: "https://upload.wikimedia.org/wikipedia/en/4/45/QueenMoviePoster7thMarch.jpg",
    releaseDate: "2014-03-07",
    year: 2014,
    runtime: 146,
    genres: ["Comedy", "Drama"],
    language: "Hindi",
    rating: 8.1,
    director: "Vikas Bahl",
    actors: [{ name: "Kangana Ranaut", character: "" }],
    description: "A woman goes on her honeymoon alone after being dumped.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 77,
  },
  {
    id: "d15",
    title: "Article 15",
    poster: "https://upload.wikimedia.org/wikipedia/en/1/1a/Article_15_Poster.jpg",
    releaseDate: "2019-06-28",
    year: 2019,
    runtime: 130,
    genres: ["Crime", "Drama"],
    language: "Hindi",
    rating: 8.1,
    director: "Anubhav Sinha",
    actors: [{ name: "Ayushmann Khurrana", character: "" }],
    description: "A police officer investigates a crime involving caste discrimination.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 75,
  },
  {
    id: "d16",
    title: "Kahaani",
    poster: "https://upload.wikimedia.org/wikipedia/en/9/9e/Kahaani_Poster.jpg",
    releaseDate: "2012-03-09",
    year: 2012,
    runtime: 122,
    genres: ["Mystery", "Thriller"],
    language: "Hindi",
    rating: 8.1,
    director: "Sujoy Ghosh",
    actors: [{ name: "Vidya Balan", character: "" }],
    description: "A pregnant woman searches for her missing husband in Kolkata.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 76,
  },
  {
    id: "d17",
    title: "Bajrangi Bhaijaan",
    poster: "https://upload.wikimedia.org/wikipedia/en/d/dd/Bajrangi_Bhaijaan_Poster.jpg",
    releaseDate: "2015-07-17",
    year: 2015,
    runtime: 163,
    genres: ["Comedy", "Drama"],
    language: "Hindi",
    rating: 8.0,
    director: "Kabir Khan",
    actors: [{ name: "Salman Khan", character: "" }],
    description: "A man helps a mute Pakistani girl reunite with her family.",
    platforms: [{ name: "Prime Video", status: "subscription", url: "https://www.primevideo.com" }],
    isFree: false,
    popularity: 79,
  },
  {
    id: "d18",
    title: "PK",
    poster: "https://upload.wikimedia.org/wikipedia/en/c/c3/PK_poster.jpg",
    releaseDate: "2014-12-19",
    year: 2014,
    runtime: 153,
    genres: ["Comedy", "Drama", "Sci-Fi"],
    language: "Hindi",
    rating: 8.1,
    director: "Rajkumar Hirani",
    actors: [{ name: "Aamir Khan", character: "" }],
    description: "An alien questions religious dogmas on Earth.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 81,
  },
  {
    id: "d19",
    title: "Swades",
    poster: "https://upload.wikimedia.org/wikipedia/en/7/7c/Swades_poster.jpg",
    releaseDate: "2004-12-17",
    year: 2004,
    runtime: 210,
    genres: ["Drama"],
    language: "Hindi",
    rating: 8.2,
    director: "Ashutosh Gowariker",
    actors: [{ name: "Shah Rukh Khan", character: "" }],
    description: "An NRI returns to India and rediscovers his roots.",
    platforms: [{ name: "YouTube", status: "free", url: "https://www.youtube.com" }],
    isFree: true,
    popularity: 74,
  },
  {
    id: "d21",
    title: "Sholay",
    poster: "https://upload.wikimedia.org/wikipedia/en/5/52/Sholay-poster.jpg",
    releaseDate: "1975-08-15",
    year: 1975,
    runtime: 204,
    genres: ["Action", "Adventure", "Comedy"],
    language: "Hindi",
    rating: 8.1,
    director: "Ramesh Sippy",
    actors: [{ name: "Amitabh Bachchan", character: "Jai" }, { name: "Dharmendra", character: "Veeru" }],
    description: "Two criminals are hired to catch a ruthless dacoit in a small village.",
    platforms: [{ name: "Prime Video", status: "subscription", url: "https://www.primevideo.com" }],
    isFree: false,
    popularity: 93,
  },
  {
    id: "d22",
    title: "Dil Chahta Hai",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/86/Dil_Chahta_Hai.jpg",
    releaseDate: "2001-08-10",
    year: 2001,
    runtime: 183,
    genres: ["Comedy", "Drama", "Romance"],
    language: "Hindi",
    rating: 8.1,
    director: "Farhan Akhtar",
    actors: [{ name: "Aamir Khan", character: "" }, { name: "Saif Ali Khan", character: "" }],
    description: "Three young friends navigate love and growing up in modern India.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 82,
  },
  {
    id: "d23",
    title: "Tumbbad",
    poster: "https://upload.wikimedia.org/wikipedia/en/4/41/Tumbbad_poster.jpg",
    releaseDate: "2018-10-12",
    year: 2018,
    runtime: 104,
    genres: ["Horror", "Fantasy", "Drama"],
    language: "Hindi",
    rating: 8.2,
    director: "Rahi Anil Barve",
    actors: [{ name: "Sohum Shah", character: "" }],
    description: "A man explores a cursed village treasure tied to an ancient goddess of greed.",
    platforms: [{ name: "Prime Video", status: "subscription", url: "https://www.primevideo.com" }],
    isFree: false,
    popularity: 76,
  },
  {
    id: "d24",
    title: "Drishyam",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/83/Drishyam_2015_film.jpg",
    releaseDate: "2015-07-31",
    year: 2015,
    runtime: 163,
    genres: ["Crime", "Drama", "Thriller"],
    language: "Hindi",
    rating: 8.2,
    director: "Nishikant Kamat",
    actors: [{ name: "Ajay Devgn", character: "" }],
    description: "A man goes to extreme lengths to protect his family after a crime.",
    platforms: [{ name: "Netflix", status: "subscription", url: "https://www.netflix.com" }],
    isFree: false,
    popularity: 84,
  },
  {
    id: "d25",
    title: "Haider",
    poster: "https://upload.wikimedia.org/wikipedia/en/0/09/Haider_Poster.jpg",
    releaseDate: "2014-10-02",
    year: 2014,
    runtime: 160,
    genres: ["Crime", "Drama", "Thriller"],
    language: "Hindi",
    rating: 8.1,
    director: "Vishal Bhardwaj",
    actors: [{ name: "Shahid Kapoor", character: "" }],
    description: "A Kashmiri student searches for his missing father in a Hamlet-inspired tragedy.",
    platforms: [{ name: "YouTube", status: "free", url: "https://www.youtube.com" }],
    isFree: true,
    popularity: 73,
  },
  {
    id: "d26",
    title: "Stree",
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4f/Stree_film_poster.jpg",
    releaseDate: "2018-08-31",
    year: 2018,
    runtime: 128,
    genres: ["Comedy", "Horror"],
    language: "Hindi",
    rating: 7.5,
    director: "Amar Kaushik",
    actors: [{ name: "Rajkummar Rao", character: "" }, { name: "Shraddha Kapoor", character: "" }],
    description: "A small town is haunted by a spirit who abducts men at night.",
    platforms: [{ name: "JioHotstar", status: "subscription", url: "https://www.hotstar.com" }],
    isFree: false,
    popularity: 79,
  },
];


export const DEMO_TV: TvProgram[] = [
  {
    channel: "Sony Max",
    movieTitle: "Today's full schedule",
    start: "00:00",
    end: "23:59",
    logo: "",
    url: "https://www.sonyliv.com",
    scheduleUrl: "https://www.epgschedule.com/channel/sony-max/",
  },
  {
    channel: "Zee Cinema",
    movieTitle: "Today's full schedule",
    start: "00:00",
    end: "23:59",
    url: "https://www.zee5.com",
    scheduleUrl: "https://www.epgschedule.com/channel/zee-cinema/",
  },
  {
    channel: "Star Gold",
    movieTitle: "Today's full schedule",
    start: "00:00",
    end: "23:59",
    url: "https://www.hotstar.com",
    scheduleUrl: "https://www.epgschedule.com/channel/star-gold/",
  },
  {
    channel: "Colors Cineplex",
    movieTitle: "Today's full schedule",
    start: "00:00",
    end: "23:59",
    url: "https://www.jiocinema.com",
    scheduleUrl: "https://www.epgschedule.com/channel/colors-cineplex/",
  },
];

export const DEMO_ACTORS: PersonResult[] = [
  { id: 0, name: "Shah Rukh Khan" },
  { id: 0, name: "Aamir Khan" },
  { id: 0, name: "Salman Khan" },
  { id: 0, name: "Deepika Padukone" },
  { id: 0, name: "Priyanka Chopra" },
  { id: 0, name: "Ranbir Kapoor" },
  { id: 0, name: "Alia Bhatt" },
  { id: 0, name: "Ayushmann Khurrana" },
  { id: 0, name: "Vicky Kaushal" },
  { id: 0, name: "Kangana Ranaut" },
  { id: 0, name: "Nawazuddin Siddiqui" },
  { id: 0, name: "Amitabh Bachchan" },
  { id: 0, name: "Shahid Kapoor" },
  { id: 0, name: "Rajkummar Rao" },
];

export const MOODS = [
  "Action",
  "Comedy",
  "Drama",
  "Romance",
  "Thriller",
  "War",
  "Family",
  "Crime",
] as const;
